title: 3rd IEEE ITSC Workshop on Intelligent and Automated Waterway Transportation
description: Edmonton, Canada, Sep. 24th, 2024

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
